core:
  build: core
  links:
    - mysql
  environment:
    - MYSQL_USER=icinga
    - MYSQL_PASSWORD=icinga
    - MYSQL_DATABASE=icinga
  volumes:
    - "/srv/docker/icinga2/etc/icinga2:/etc/icinga2"

web:
  build: web
  links:
    - mysql
    - core
  ports:
    - "8080:80"
  environment:
    - MYSQL_USER=icinga
    - MYSQL_PASSWORD=icinga
    - MYSQL_DATABASE=icinga

mysql:
  image: mariadb
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=icinga
    - MYSQL_PASSWORD=icinga
    - MYSQL_DATABASE=icinga
